### ISSUE TITLE
Does Not Work With Aether Legacy

### ISSUE THREAD

**Issue by EmosewaGamer** [Darkhax-Minecraft/DimensionStages#1]
So, it seems that even though I have:
mods.DimensionStages.addDimensionStage("a", 4);

 I can walk through the portal to the Aether without having that stage.

**Comment by darkhax** [comment]
This is an issue with Aether Legacy, they are not firing the forge event like they should. Please report this issue to them. Could you please include a reference to [this](https://github.com/TeamTwilight/twilightforest/issues/171) issue, and [this](https://github.com/MinecraftForge/MinecraftForge/blob/bbf1bef7d31ccf297af7253b880ba7575f3f17bd/src/main/java/net/minecraftforge/common/ForgeHooks.java#L1043-L1056) code. Those two things should help make it much easier for them to fix it.

**Comment by EmosewaGamer** [comment]
Yeah, I figured it was on their side.

**Comment by EmosewaGamer** [comment]
Ok, they fixed it in the latest version.
