### ISSUE TITLE
[Suggestion] Creative mode player can access any dimensions without stages

### ISSUE THREAD

**Issue by GoldenTotem** [Darkhax-Minecraft/DimensionStages#11]
I think that creative mode players should access any dimensions without stages. But I cannot find the configuration of it in 1.12.2 or 1.16.5. So I think there should be a configuration to choose whether creative players don't need stages or any player need stages.

**Comment by Darkhax** [comment]
This feature has been added to the 1.19.2 version of the mod. Look for the `dimstages.json` file in the games config folder.

**Comment by GoldenTotem** [comment]
> This feature has been added to the 1.19.2 version of the mod. Look for the `dimstages.json` file in the games config folder.

Could you please give a backport to 1.16.5? I really need it, thx
