### ISSUE TITLE
[QUESTION] [1.20.1]

### ISSUE THREAD

**Issue by Iker21dev** [Darkhax-Minecraft/DimensionStages#12]
### Question

well I just wanted to see if there is any interest in this being updated.

**Comment by CPearl0** [comment]
I have ported it to 1.20.1. You can get at https://www.curseforge.com/minecraft/mc-mods/re-dimension-stages.

**Comment by Darkhax** [comment]
Hello, development of GameStages and the official addons has been temporarily paused while I focus on porting on other mods. There is no roadmap for when this mod will be updated, and it likely won't come to 1.20.1 officially.
