### ISSUE TITLE
I know this is not an issue but...

### ISSUE THREAD

**Issue by Mr-Syntax** [Darkhax-Minecraft/DimensionStages#7]
can some kind hearted soul please tell me how i can restrict access to "The Abyss" untill the ender dragon has been slain?

im a complete noob at coding sorry

**Comment by Darkhax** [comment]
You would create a new stage called "abyss" or something similar, and then stage their dimension to that stage. You can then use the [StageHelper](https://docs.blamejared.com/1.16/en/mods/GameStages/StageHelper#give-stage-on-advancement) to give a stage when the advancement is given to the player, or you can specifically track [when a mob dies](https://docs.blamejared.com/1.16/en/mods/GameStages/StageHelper#give-stage-on-mob-kill).
